export const ADD_WORKTIME_BEGINS = 'ADD_WORKTIME_BEGINS';
export const ADD_WORKTIME_SUCCESS = 'ADD_WORKTIME_SUCCESS';
export const ADD_WORKTIME_FAILURE = 'ADD_WORKTIME_FAILURE';

export const GET_WORKTIMES_BEGINS = 'GET_WORKTIMES_BEGINS';
export const GET_WORKTIMES_SUCCESS = 'GET_WORKTIMES_SUCCESS';
export const GET_WORKTIMES_FAILURE = 'GET_WORKTIMES_FAILURE';

export const UPDATE_WORKTIME_BEGINS = 'UPDATE_WORKTIME_BEGINS';
export const UPDATE_WORKTIME_SUCCESS = 'UPDATE_WORKTIME_SUCCESS';
export const UPDATE_WORKTIME_FAILURE = 'UPDATE_WORKTIME_FAILURE';

export const DELETE_WORKTIME_BEGINS = 'DELETE_WORKTIME_BEGINS';
export const DELETE_WORKTIME_SUCCESS = 'DELETE_WORKTIME_SUCCESS';
export const DELETE_WORKTIME_FAILURE = 'DELETE_WORKTIME_FAILURE';
